### ISSUE TITLE
any hope to convert this theme to VSCode?

### ISSUE THREAD

**Issue by florinpatrascu** [lytedev/lyte-theme#14]
Thank you, it's a beautiful theme. would be nice if it can be reincarnated into into a VSCode compatible theme ❤️

**Comment by lytedev** [comment]
I'm afraid not. I use [vim][vim-dotfiles] full time these days and am unfamiliar with VSCode's theming capabilities.

However, if you wanna give it a shot, I'm all for it!

[vim-dotfiles]: https://github.com/lytedev/dotfiles/tree/master/apps/neovim
