### ISSUE TITLE
Error showing window name in Sublime 3 on Mac OS X

### ISSUE THREAD

**Issue by ashton** [lytedev/lyte-theme#9]
There is an error showing the file name on tabs, in sublime 3 on mac os x.

![captura de tela 2014-09-06 as 18 00 05](https://cloud.githubusercontent.com/assets/95974/4176545/b2caa21a-3609-11e4-8c4a-00beff666202.png)

**Comment by lytedev** [comment]
Closing this unless it becomes a real problem? Somehow I doubt the theme caused this,
